/**
 * Static generator for the case-study library.
 *
 *   content/case-studies/<project>/<slug>.md   →  case-studies/<project>/<slug>.html
 *                                          →  assets/case-studies.json   (search index)
 *                                          →  case-studies/index.html    (library)
 *
 * Deliberately dependency-free so CI is just `node scripts/build.mjs` —
 * no install step, nothing to audit on a public repo.
 *
 * Authoring format is a small, documented subset (see README):
 *   front matter  — key: value | key: [a, b] | key: | block | key: - list
 *   body          — "## Eyebrow · Title" starts a section
 *                   "### Heading" + list  becomes a collapsible notes block
 *                   raw HTML passes straight through
 */
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  unlinkSync,
  statSync,
  existsSync,
} from "node:fs";
import { join, relative, dirname, basename } from "node:path";

import { esc } from "./lib/html.mjs";
import { parseFrontMatter, renderBody } from "./lib/markdown.mjs";
import { SITE, page, libraryPage, learningPathPage } from "./lib/render.mjs";

const ROOT = process.cwd();
const CONTENT = join(ROOT, "content/case-studies");

const GENERATED = "<!-- Generated by scripts/build.mjs; edit sources under content/. -->\n";
const checkOnly = process.argv.includes("--check");
const outputs = new Map();
const emit = (url, html) => {
  if (outputs.has(url)) throw new Error(`Duplicate generated path: ${url}`);
  outputs.set(url, html);
};

// Only named slots are expanded; prose, diagrams, and inline scripts stay intact.
function template(source, values) {
  return source.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    if (!Object.hasOwn(values, key)) throw new Error(`Unknown template slot: ${key}`);
    return values[key];
  });
}

/* ------------------------------------------------------------------ utils */

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (name.endsWith(".md")) out.push(p);
  }
  return out;
}

function walkHtml(dir) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walkHtml(p));
    else if (name.endsWith(".html")) out.push(p);
  }
  return out;
}

/* ---------------------------------------------------------------- build */
const files = walk(CONTENT).sort();
const projects = JSON.parse(readFileSync(join(ROOT, "content/projects.json"), "utf8"));
const projectMap = new Map();
for (const project of projects) {
  if (!/^[a-z0-9-]+$/.test(project.id) || !project.name || projectMap.has(project.id))
    throw new Error(`Invalid or duplicate project: ${project.id}`);
  projectMap.set(project.id, project);
}
if (!files.length) {
  console.error("No content found under content/case-studies/");
  process.exit(1);
}

const docs = files.map((file) => {
  const { data, body } = parseFrontMatter(readFileSync(file, "utf8").replaceAll("\r\n", "\n"), file);
  for (const req of ["title", "project", "summary"])
    if (!data[req]) throw new Error(`${file}: front matter missing "${req}"`);
  const slug = basename(file, ".md");
  const project = projectMap.get(data.project);
  if (!project || basename(dirname(file)) !== data.project || !/^[a-z0-9-]+$/.test(slug))
    throw new Error(`${file}: invalid project, folder, or slug`);
  if (data.layout) throw new Error(`${file}: all case studies use the shared layout; put sections in the body and scripts in assets/`);
  if (data.scaffold !== undefined && !["true", "false"].includes(data.scaffold)) throw new Error(`${file}: scaffold must be true or false`);
  for (const key of ["projectName", "engagement"])
    if (Object.hasOwn(data, key)) throw new Error(`${file}: ${key} is derived from content/projects.json`);
  if (data.order !== undefined && !Number.isFinite(Number(data.order))) throw new Error(`${file}: order must be a number`);
  for (const key of ["stack", "tags", "scripts", "outcomes", "flow"])
    if (data[key] !== undefined && !Array.isArray(data[key])) throw new Error(`${file}: ${key} must be a list`);
  const url = `case-studies/${data.project}/${slug}.html`;
  return { ...data, projectName: project.name, slug, url, file,
    bodyHtml: renderBody(body) };
});

docs.sort(
  (a, b) =>
    projects.findIndex((p) => p.id === a.project) - projects.findIndex((p) => p.id === b.project) ||
    Number(a.order || 0) - Number(b.order || 0) || a.slug.localeCompare(b.slug),
);

let written = 0;
docs.forEach((d, idx) => {
  const prev = docs[idx - 1]?.project === d.project ? docs[idx - 1] : null;
  const next = docs[idx + 1]?.project === d.project ? docs[idx + 1] : null;
  const depth = d.url.split("/").length - 1;
  const up = "../".repeat(depth);
  emit(d.url, page(d, d.bodyHtml, { up, url: d.url, prev, next }));
  written++;
  console.log("  page  ", d.url);
});

// search index — the single source of truth for the library and assistant
const index = docs.map((d) => ({
  title: d.title,
  nav: d.nav || d.title,
  summary: d.summary,
  project: d.project,
  projectName: d.projectName || d.project,
  layer: d.layer || "",
  stack: d.stack || [],
  tags: d.tags || [],
  url: d.url,
  problem: (d.problem || "").replace(/\s+/g, " ").trim(),
  solution: (d.solution || "").replace(/\s+/g, " ").trim(),
}));

emit("assets/case-studies.json", JSON.stringify(index, null, 2) + "\n");
emit("case-studies/index.html", libraryPage(index));

const selectedWork = projects.map((project, projectIndex) => {
  const studies = docs.filter((d) => d.project === project.id);
  const engagementUrl = `case-studies/${project.id}/index.html`;
  const values = { projectName: esc(project.name), engagementUrl: esc(engagementUrl), projectNumber: String(projectIndex + 1).padStart(2, "0") };
  const caseStudyLinks = studies.map((d, idx) => `            <a href="${esc(basename(d.url))}"><span>${String(idx + 1).padStart(2, "0")} / ${esc(d.label || d.layer || "Case study")}</span><strong>${esc(d.nav || d.title)}</strong><small>${esc(d.summary)} →</small></a>`).join("\n");
  if (project.customOverview) {
    const overviewBase = join(ROOT, `content/overviews/${project.id}`);
    const sources = [".html", ".md"].filter((extension) => existsSync(overviewBase + extension));
    if (sources.length !== 1) throw new Error(`${project.id}: provide exactly one HTML or Markdown overview`);
    const source = readFileSync(overviewBase + sources[0], "utf8").replaceAll("\r\n", "\n");
    const slots = { ...values, caseStudyLinks, caseStudyCount: studies.length };
    if (sources[0] === ".md") {
      const { data, body } = parseFrontMatter(source, overviewBase + ".md");
      if (!data.title || !data.summary) throw new Error(`${project.id}: overview requires title and summary`);
      emit(engagementUrl, page({ ...data, projectName: project.name }, template(renderBody(body), slots), { up: "../../", url: engagementUrl }));
    } else {
      emit(engagementUrl, template(source, slots));
    }
  } else {
    emit(engagementUrl, page({ title: project.name, projectName: project.name,
      summary: "Explore the case studies from this engagement, including the problems, architecture decisions, and outcomes." },
      `<section><div class="wrap"><h2>Case studies</h2><div class="case-study-links">${caseStudyLinks}</div></div></section>`,
      { up: "../../", url: engagementUrl }));
  }
  return template(readFileSync(join(ROOT, `content/engagements/${project.id}.html`), "utf8"), values).trimEnd();
}).join("\n");
emit("index.html", template(readFileSync(join(ROOT, "content/home.html"), "utf8"), { selectedWork, engagementCount: projects.length }));

// learning paths and playbooks
const LEARNING_PATHS_DIR = join(ROOT, "content/learning-paths");
if (existsSync(join(LEARNING_PATHS_DIR, "tracks.json"))) {
  const tracks = JSON.parse(readFileSync(join(LEARNING_PATHS_DIR, "tracks.json"), "utf8"));
  const hubSourcePath = join(LEARNING_PATHS_DIR, "index.html");
  if (existsSync(hubSourcePath)) {
    emit("learning-paths/index.html", readFileSync(hubSourcePath, "utf8"));
  }

  for (const track of tracks) {
    const trackDir = join(LEARNING_PATHS_DIR, track.id);
    if (!existsSync(trackDir)) continue;

    const trackFiles = walk(trackDir).sort();
    const moduleFiles = trackFiles.filter((f) => basename(f) !== "index.md");
    const overviewFile = trackFiles.find((f) => basename(f) === "index.md");

    const modules = moduleFiles.map((file) => {
      const { data, body } = parseFrontMatter(readFileSync(file, "utf8").replaceAll("\r\n", "\n"), file);
      const slug = basename(file, ".md");
      const url = `learning-paths/${track.id}/${slug}.html`;
      return {
        ...data,
        slug,
        url,
        file,
        bodyHtml: renderBody(body),
        module: Number(data.module || data.order || 0),
        totalModules: data.totalModules || moduleFiles.length,
      };
    });

    modules.sort((a, b) => a.module - b.module || a.slug.localeCompare(b.slug));

    modules.forEach((mod, idx) => {
      const prev = modules[idx - 1] || null;
      const next = modules[idx + 1] || null;
      emit(mod.url, learningPathPage(mod, mod.bodyHtml, { up: "../../", url: mod.url, prev, next, track }));
      written++;
      console.log("  playbook", mod.url);
    });

    if (overviewFile) {
      const { data, body } = parseFrontMatter(readFileSync(overviewFile, "utf8").replaceAll("\r\n", "\n"), overviewFile);
      const overviewUrl = `learning-paths/${track.id}/index.html`;
      emit(
        overviewUrl,
        learningPathPage(
          { ...data, totalModules: modules.length },
          renderBody(body),
          { up: "../../", url: overviewUrl, track }
        )
      );
      written++;
      console.log("  track   ", overviewUrl);
    }
  }
}

// Derive discovery files from the actual page canonicals, including custom overviews.
const canonicalUrls = new Set();
for (const [url, html] of outputs) {
  if (!url.endsWith(".html")) continue;
  const matches = [...html.matchAll(/<link\s+rel="canonical"\s+href="([^"]+)"\s*\/?>/g)];
  if (matches.length !== 1) throw new Error(`${url}: expected exactly one canonical URL`);
  const canonical = matches[0][1];
  const allowed = [`${SITE}/${url}`, `${SITE}/${url.replace(/index\.html$/, "")}`];
  if (!allowed.includes(canonical) || canonicalUrls.has(canonical))
    throw new Error(`${url}: invalid or duplicate canonical URL: ${canonical}`);
  canonicalUrls.add(canonical);
}
emit("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...canonicalUrls].sort().map((url) => `  <url><loc>${esc(url)}</loc></url>`).join("\n")}
</urlset>
`);
emit("robots.txt", `User-agent: *\nAllow: /\n\nSitemap: ${SITE}/sitemap.xml\n`);
emit("feed.xml", `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Prudhvi Raj Anupoju — Cloud Platform Architecture Case Studies</title>
    <link>${SITE}/case-studies/</link>
    <description>Enterprise cloud architecture case studies covering governance, resilience, integration, and cost optimization.</description>
    <language>en</language>
    <atom:link href="${SITE}/feed.xml" rel="self" type="application/rss+xml"/>
${docs
  .map(
    (d) => `    <item>
      <title>${esc(d.title)}</title>
      <link>${SITE}/${d.url}</link>
      <guid>${SITE}/${d.url}</guid>
      <description>${esc(d.summary || "")}</description>
      <category>${esc(d.layer || d.projectName)}</category>
    </item>`,
  )
  .join("\n")}
  </channel>
</rss>
`);

// Validate and render everything before touching outputs. Never delete unknown HTML.
let stale = false;
for (const [url, source] of outputs) {
  const output = url.endsWith(".html") ? source.replace("<!doctype html>", `<!doctype html>\n${GENERATED.trimEnd()}`) : source;
  const file = join(ROOT, url);
  if (checkOnly) {
    let current;
    try { current = readFileSync(file, "utf8"); } catch (error) { if (error.code !== "ENOENT") throw error; }
    if (current?.replaceAll("\r\n", "\n") !== output.replaceAll("\r\n", "\n")) {
      console.error(`Stale generated output: ${url}`);
      stale = true;
    }
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, output);
  }
}
for (const dir of ["case-studies", "learning-paths"]) {
  for (const file of walkHtml(join(ROOT, dir))) {
    const url = relative(ROOT, file).replaceAll("\\", "/");
    if (!outputs.has(url) && readFileSync(file, "utf8").includes(GENERATED.trim())) {
      if (checkOnly) { console.error(`Obsolete generated output: ${url}`); stale = true; }
      else { unlinkSync(file); console.log("  remove ", url); }
    }
  }
}
if (stale) process.exitCode = 1;
console.log(`\n${checkOnly ? "Checked" : "Built"} ${written} pages, homepage, overviews, playbooks, library, and search index.`);
